[package]
name = "plus-engine"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true
html5ever.workspace = true
markup5ever_rcdom.workspace = true
cssparser.workspace = true
regex.workspace = true
